version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    fpm:
      build:
        context: .
        dockerFile: docker/Fpm.Dockerfile
      values:
        - /:/var/www/laravel-docker
      links:
        - mysql
    mysql:
      image: mysql:5.7
      ports:
        - 33861:3306
      environment:
        - MYSQL ROOT PASSWORD=root
        - MYSQL_DATABASE = test
